const fakeActivities = [
  'Visit museums',
  'Go shopping',
  'Explore national parks',
  'Go hiking',
  'Take a guided city tour',
  'Visit historical landmarks',
  'Attend cultural festivals',
  'Try local cuisine',
  'Take a scenic drive',
  'Go on a wine tasting tour',
  'Visit amusement parks',
  'Take a boat tour',
  'Go on a hot air balloon ride',
  'Try adventure sports like bungee jumping or ziplining',
  'Go on a safari',
  'Visit art galleries',
  'Go to the beach',
  'Attend a live concert or show',
  'Take a bike tour',
  'Try water sports like surfing or kayaking',
  'Visit ancient ruins',
  'Go skiing or snowboarding',
  'Take a cooking class',
  'Go on a brewery tour',
  'Attend a sporting event',
  'Take a yoga or wellness retreat',
  'Visit botanical gardens',
  'Go on a wildlife tour',
  'Explore local markets',
  'Visit zoos or aquariums',
  'Take a dance class',
  'Go on a ghost tour',
  'Try scuba diving or snorkeling',
  'Take a photography tour',
  'Visit cathedrals or churches',
  'Go on a train journey',
  'Attend a language school',
  'Take a helicopter or plane tour',
  'Visit planetariums or observatories',
  'Go on a walking tour',
  'Take a pottery or ceramics class',
  'Visit science museums',
  'Go on a river cruise',
  'Try horseback riding',
  'Attend a music festival',
  'Take a balloon ride',
  'Visit historical homes or estates',
  'Mountain Bike',
  'Traking',
  'Outdoor Yoga',
]

const seasonList = ['Summer', 'Aurumn', 'Spring', 'Winter']

module.exports = {
  fakeActivities,
  seasonList,
}
